// GENERATED by build/gen_sw.py -- do not edit by hand.
// Precaches the whole app (shell + icons + every audio sample) so it works
// with no network at all, including airplane mode on a cold start.
const CACHE = 'avar-course-a7db183662a0';
const PRECACHE = ["./","./index.html","./manifest.json","./icon-192.png","./icon-512.png","./icon-180.png","./audio/a.mp3","./audio/b.mp3","./audio/ch.mp3","./audio/chI.mp3","./audio/d.mp3","./audio/e.mp3","./audio/g.mp3","./audio/gI.mp3","./audio/gh.mp3","./audio/h.mp3","./audio/hI.mp3","./audio/hy.mp3","./audio/i.mp3","./audio/j.mp3","./audio/k.mp3","./audio/kI.mp3","./audio/kh.mp3","./audio/kkh.mp3","./audio/l.mp3","./audio/lh.mp3","./audio/lhI.mp3","./audio/m.mp3","./audio/n.mp3","./audio/o.mp3","./audio/p.mp3","./audio/q.mp3","./audio/qI.mp3","./audio/qh.mp3","./audio/r.mp3","./audio/s.mp3","./audio/sh.mp3","./audio/t.mp3","./audio/tI.mp3","./audio/ts.mp3","./audio/tsI.mp3","./audio/u.mp3","./audio/w.mp3","./audio/z.mp3","./audio/zh.mp3"];
const OFFLINE_URL = './index.html';

// Cache each entry on its own: one bad response must not abort the install and
// leave the user with nothing cached.
async function precache() {
  const c = await caches.open(CACHE);
  const bust = { cache: 'reload' };
  await Promise.all(PRECACHE.map(async url => {
    try {
      const res = await fetch(new Request(url, bust));
      if (res && (res.ok || res.type === 'opaque')) await c.put(url, res);
    } catch (e) { /* keep going; the fetch handler will fill it in later */ }
  }));
}

self.addEventListener('install', e => {
  e.waitUntil(precache().then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    const ks = await caches.keys();
    await Promise.all(ks.filter(k => k !== CACHE && k.startsWith('avar-course-'))
                        .map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

// Report/repair precache state so the app can show whether it is genuinely
// ready for offline use, and top itself up if anything is missing.
async function status() {
  const c = await caches.open(CACHE);
  const have = new Set((await c.keys()).map(r => new URL(r.url).pathname));
  const missing = PRECACHE.filter(u => !have.has(new URL(u, self.location).pathname));
  return { total: PRECACHE.length, cached: PRECACHE.length - missing.length, missing, version: CACHE };
}

self.addEventListener('message', e => {
  const d = e.data;
  if (d === 'skipWaiting') { self.skipWaiting(); return; }
  if (d && d.type === 'status' && e.ports && e.ports[0]) {
    const port = e.ports[0];
    e.waitUntil(status().then(s => port.postMessage(s),
                              () => port.postMessage({ total: PRECACHE.length, cached: 0, missing: PRECACHE, error: true })));
  }
  if (d && d.type === 'repair' && e.ports && e.ports[0]) {
    const port = e.ports[0];
    e.waitUntil(precache().then(status).then(s => port.postMessage(s),
                                             () => port.postMessage({ total: PRECACHE.length, cached: 0, error: true })));
  }
});

async function cacheFirst(request, fallbackUrl) {
  const cached = await caches.match(request, { ignoreSearch: true, ignoreVary: true });
  if (cached) return cached;
  try {
    const res = await fetch(request);
    if (res && res.ok && new URL(request.url).origin === self.location.origin) {
      const copy = res.clone();
      caches.open(CACHE).then(c => c.put(request, copy)).catch(() => {});
    }
    return res;
  } catch (e) {
    if (fallbackUrl) {
      const fb = await caches.match(fallbackUrl);
      if (fb) return fb;
    }
    return new Response('', { status: 504, statusText: 'Offline' });
  }
}

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  // Navigations always resolve to the cached app shell when the network is gone.
  if (req.mode === 'navigate') { e.respondWith(cacheFirst(req, OFFLINE_URL)); return; }
  if (new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(cacheFirst(req, null));
});
